### ISSUE TITLE
The docs landing pages looks misaligned

### ISSUE THREAD

**Issue by anthonydillon** [canonical/juju.is#246]
The new docs landing page looks misaligned. With the combination of the double navigation, search strip and offset main content.

![image](https://user-images.githubusercontent.com/1413534/119401198-13b9d800-bcd3-11eb-80ca-e51c617d80e8.png)

**Comment by spencerbygraves** [comment]
@danielmutis should the Content guide at the bottom be a left nav?

**Comment by danielmutis** [comment]
@spencerbygraves I believe this was done following a copydoc from David. I find it difficult to navigate, especially if you are a recurring visitor of the docs and don't need this "guided" style of intro. Maybe this should just be an intro page to the docs, and we keep the normal side navigation visible so people can navigate wherever they need to go.

**Comment by clagom** [comment]
I think we wanted to explore a different kind of landing page for docs, in the past we had some explorations and an initial research from @wgx and @amylily1011 (requests originated from Juju core and MAAS core). 
Based on those findings and research, I think it's not unreasonable to have a "special" landing page with a different layout than the inner doc pages. If we take this opportunity to make a solution that can be extended (even just as an option) to other teams and docs, I think it would be valuable.
In this case for instance, the intent is clear (guide users rather than leaving them explore the navigation), but uses a fixed layout.

**Comment by Lukewh** [comment]
The addition of the navigation and general updates have resolved this issue.
