### ISSUE TITLE
Make table of content levels collapsible [JUJU-164]

### ISSUE THREAD

**Issue by tmihoc** [canonical/juju.is#360]
Specifically, the left-hand side tables of contents on https://juju.is/docs/olm and https://juju.is/docs/sdk are too long and it's easy to get lost in content. Making the levels collapsible should improve document discoverability.

**Comment by bartaz** [comment]
Hi @tmihoc, I'm Bartek from Vanilla team and this issue has been brought to our attention after catch-up you had with Robin.

We are currently working on expandable side navigation in Vanilla (https://github.com/canonical-web-and-design/vanilla-framework/issues/4122), but I think it would be good to be on the same page to make sure that what we propose would solve your problems.

I had a look at the links that you posed as examples of long side navigation in Juju docs ( https://juju.is/docs/olm and https://juju.is/docs/sdk) but it seems that maybe they changed since? Because they don't seem to have long side navigation (they seem to use minimal side navigation now). Do you have other examples where you'd like to see expanding sections work?

Thanks!

**Comment by tmihoc** [comment]
So sorry, I meant to reply but was in the middle of something else and then forgot. So, what you're seeing is a coping mechanism---because we had too many entries and they resulted in an endlessly long TOC, we decided to set all the non-main levels to null, so they wouldn't show in the margins at all. We're eagerly waiting for the Web team to make the TOC levels collapsible so we can restore them all.

**Comment by tmihoc** [comment]
Hi everyone, any progress on this? People are really missing a comprehensive side navigation bar in juju.is/docs, but I can't give them that before we get collapsible levels, as the list would be too long and as a result incomprehensible.

**Comment by solmyrcan** [comment]
Having a navigation pane on the left side of Juju docs would greatly help readers so that they could trace where they are in the entirety of the doc pages. I've gone through almost all Juju doc pages, and what I most suffered from was not the content, but the fact that I lost tack of where I came from a page, and had to navigate back via the browsers, which wasn't a happy experience :) I also ended up with opening so many tabs due to the same reason. If we had a navigation pane with all content there, I believe the pane would need to be collapsible, as there are quite a few pages.

**Comment by clagom** [comment]
HI @tmihoc, @danielmutis presented this work in the "Documentation/web team sync" today.
@solmyrcan the lack of additional pages in the side navigation doesn't depend on this work, this is to add the collapse functionality to the side navigation.

**Comment by tmihoc** [comment]
The minute I can start using collapsible levels in the Navigation, I will add all the pages back in.

**Comment by danielmutis** [comment]
@tmihoc I sent this on an email but just to keep track on here: 

During the call, I shared the prototypes of the expand-collapse behaviour on the side navigation. The 3 options presented can be found on[ this link](https://www.figma.com/proto/oo1qFi0ufIXRXJ1jJndsjz/Side-Nav---Expand?page-id=0%3A1&node-id=2%3A2&starting-point-node-id=2%3A2&show-proto-sidebar=1), and are as follows:
* Flow 1: use of accordions to indicate what elements expand and collapse. The items that expand can’t be content pages simultaneously, so we would rely on overview pages for the introduction content. 
* Flow 2: no visual cue that indicates that something will expand. This option allows expandable items to be pages as well. 
* Flow 3: a combination of the above. On level 0 of navigation, we would have the solution with no chevrons, so that we can have content pages for those items; and there would be chevrons on levels 1 and 2 when they are expandable. 

To test the prototype follow these steps:
1. Click on “Tutorials” to see the expandable behaviour.
2. Click on “Installing the appliance” to see the difference between an expandable item and a page. 
3. Click on “How to” to expand a second item.
4. Click on “Install Anbox Cloud” to expand a lower level item on the nav.
5. Click on “Deploy with Juju” to see what happens when switching pages.
6. Click on “Tutorials” again. 

Notes from the meeting:
* The prototype was received well, with a preference for options 2 and 3. Testing could be useful to determine whether they are all clear enough and to take the decision on which is most effective.
* There were concerns about not having more than 3 levels in the navigation (2 expandable). I would suggest that when the need for any further level of navigation arises, the docs and UX teams work together in finding an optimal solution. This component is used in several places, and not always by members of either the UX or the docs team, so we are apprehensive about allowing an indefinite amount of levels.

**Please take a look at these options and let me know which one fits your documentation set best, and why.**

**Comment by tmihoc** [comment]
> @tmihoc I sent this on an email but just to keep track on here:

Just saw it. I am not sure I understand the limitation "Expandable items can't have a chevron and be pages at the same time". But, assuming that's a hard constraint and Flows 1-3 are really the only options, my preference ranking for Juju docs right now is: Flow 1 > Flow 2 > Flow 3 (that's because I can't image a case where I want a page for an expandable item at level 0 more than for the more nested levels).

**Comment by clagom** [comment]
@tmihoc This has been discussed in the previous meetings. We work on components and patterns that aim to be usable and accessible. Having two different interactions (chevron and selection) on the same component is conflicting.
Our side navigation is used across all our websites and web applications; the documentation pages would therefore need to use the same component with the same interaction patterns in order to be consistent with the rest.
The proposals that @danielmutis presented answer to the need of multi-level collapsible side navigation without breaking our component and interaction patterns.

> I am not sure I understand the limitation "Expandable items can't have a chevron _and_ be pages at the same time".

**Comment by tmihoc** [comment]
I have unfortunately not been able to attend the meetings. But I was sure there were good reasons for it, along the lines you described. I just didn't know what they were. Thanks for explaining!

**Comment by anthonydillon** [comment]
Isn't the table of contents component different from the navigation we discussed previously?

**Comment by sparkiegeek** [comment]
@tmihoc i think this can be closed now?
