### ISSUE TITLE
Line width varies from regular text to list and code

### ISSUE THREAD

**Issue by tmihoc** [canonical/juju.is#369]
Example here: https://juju.is/docs/olm/manual-setup#heading--limitations . See also screenshot below.

![image](https://user-images.githubusercontent.com/38667005/145399532-d2af912c-0fa4-4833-8f2d-a362781fedda.png)

I think the line width should be the same everywhere (except maybe for tables, although I think it would overall look more polished if we made no exception).

**Comment by anthonydillon** [comment]
@lyubomir-popov would you mind picking this one up.

**Comment by lyubomir-popov** [comment]
We recently discussed this in the vanilla catchup, and the decision was:
- not to set default max-width for lists, as this would require extensive testing that would delay the 3.0 release
- not to introduce a utility that sets max-width on lists or arbitrary elements

Given we're not doing this at  framework level, we're left with the same choice but at downstream level, so you could either do one of the two above, or introduce a local text-list component that has max-width. cc @bartaz

**Comment by bartaz** [comment]
Because the content comes from discourse we can't really add any utility or component to fix that, because it's just plain `<ol>` `<ul>` element. So to solve it on Vanilla level we would need to change default width of those and deal with consequences, but this would need to happen post 3.0.

Other solution is to provide local styling for it, trying to target only the lists that we know are text content, so maybe something along the lines of:
```
main ul, main ol { max-width: 40rem }
```

And the question is - is it just about lists, or also about block content (code blocks, notifications, tables, etc) - if so, it should be changed on a container level, not individual elements.

**Comment by lyubomir-popov** [comment]
I'd say just lists. Block level elements should fill their parent container.

**Comment by anthonydillon** [comment]
What about setting:
```css
p {
    max-width: none;
}
```
for discourse docs rendering?

**Comment by lyubomir-popov** [comment]
If there's no danger of `main` ever getting wider than it currently is, I guess it is an option. It will set a bad precedent though ans I expect to see this as a local hack on every site in no time.

**Comment by tmihoc** [comment]
PS Tables are also of a different width. It's noticeable (somebody just mentioned to me that it strikes them as strange). Imo all content on a page should have the same width.

**Comment by achilleasa** [comment]
Here is an [example](https://juju.is/docs/olm/supported-features) of what @tmihoc mentioned above:

![image](https://user-images.githubusercontent.com/616049/146156738-36a48334-8019-4dea-97ed-14aa89ad5599.png)

The doc page seems to be using a grid layout so the parent container (`<main>` element) already has a fixed size. Is there a particular reason why paragraph elements within need to have a `max-width` restriction? In my view, it breaks the flow of text and makes the content harder to read as it forces users to scroll further down to read the entire block of text.

**Comment by bartaz** [comment]
>  Is there a particular reason why paragraph elements within need to have a `max-width` restriction?

Yes, text elements have limited max-width to improve readability. Research shows that (especially for longer chunks of text) keeping the width to 50-75 characters makes the text easier to follow.

If we remove max-width restriction and make text full width it will result in something like that:

<img width="851" alt="Screenshot 2021-12-15 at 10 15 04" src="https://user-images.githubusercontent.com/83575/146158339-a2be87c0-0deb-4b61-bc9f-d15705d0bc23.png">

While it may not be completely unreadable (especially in case of such short paragraph) it would affect longer documentation pages.

The other way around would be to limit everything to same max-width. This could be somehow achieved by using `col-7` instead of `col-9` in the grid.

<img width="866" alt="Screenshot 2021-12-15 at 10 20 11" src="https://user-images.githubusercontent.com/83575/146158694-9ec5aee5-800f-4bd5-9e67-1f04a3becb11.png">

This way all text and block elements will use the same width, removing the outliers. But you completely waste the space on the right side of the page, that could be useful for block elements (larger chunks of code or tables with many columns).

The styles we currently have in Vanilla were designed and built to make most of the pages work well out of the box. This may result in some outliers (when there is only one paragraph and one table), but it's hard to make something that would fit such edge cases by default. And unfortunately keeping the docs content on discourse doesn't allow us to add any specific styling to such cases.

**Comment by tmihoc** [comment]
Either option looks good to me.

**Comment by tmihoc** [comment]
Actually, having thought about it some more, I think the best would be for the text width to always match the line width. So, the wide width option you presented above.

**Comment by anthonydillon** [comment]
It seems request here is to remove the max-width on text elements within docs. If we did that locally here that would caused little impact as the text is already constricted by the side navigation. But would lead to inconsistencies across documentation sets.

@lyubomir-popov @bartaz 
Do you have a strong justification not to remove the max-width? 
If so, do you have suggestions?
Should the solution be developed locally here and proposed to the docs layout or developed directly in Vanilla and rolled out?

**Comment by lyubomir-popov** [comment]
IMO, the ideal solution is to:

a) ensure list, notifications etc align with the existing max-width (as @bartaz has mentioned above, it is there for a reason)
b) allow block elements (tables, images, code blocks, etc) to stretch to fill the parent. 

The end result would look like this:

![image](https://user-images.githubusercontent.com/2741678/169977475-48921a74-2343-4924-adcb-926870d1f9e5.png)

That said, I'm fully aware there are existing limitations that might make this tricky. If we can't get around them (e.g. limitations imposed by using discourse, as the backend for this, etc), then alternative solutions would be a (hopefully) graceful fallback/compromise. I do not mind such a compromise locally, if we decide that's the most sensible solution given the limitations, but we certainly shouldn't look to upstream a compromise.

What I think we couldtry at vanilla level is to impose a max-width on `<ul>` and `<ol>` elements, and then unset it in components that use lists to mark up other content like navigation, etc.

**Comment by tmihoc** [comment]
IMO line width should be the same throughout a doc, otherwise things just look unpolished. Content like tables and code that might benefit from more width should just come with a horizontal scroll. That's standard e.g. on stackoverflow.
